### ISSUE TITLE
Can not build wheels - `conan` error?

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/s2let#51]
See CI run https://github.com/astro-informatics/sleplet/actions/runs/5835582713/job/15827454728

```
CMake Error at /tmp/pip-build-env-v9489vrb/overlay/lib/python3.10/site-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:245 (find_package):
  By not providing "FindPythonInterp.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PythonInterp", but CMake did not find one.

  Could not find a package configuration file provided by "PythonInterp" with
  any of the following names:

    PythonInterpConfig.cmake
    pythoninterp-config.cmake

  Add the installation prefix of "PythonInterp" to CMAKE_PREFIX_PATH or set
  "PythonInterp_DIR" to a directory containing one of the above files.  If
  "PythonInterp" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:49 (find_package)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/tmp/pip-build-env-v9489vrb/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
    env = cmkr.configure(
  File "/tmp/pip-build-env-v9489vrb/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 357, in configure
    raise SKBuildError(msg)

```

**Comment by mdavezac** [comment]
Please try with pys2let version 2.2.6.

**Comment by jasonmcewen** [comment]
@paddyroddy , @mdavezac has fixed this now.  Please update to version 2.2.6.  The issue was that cmake deprecated some pythong stuff.  Thanks @mdavezac !

**Comment by paddyroddy** [comment]
Yep that works!
